# Generated by Django 4.2.5 on 2023-09-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_name', models.CharField(max_length=100)),
                ('current_day', models.DateField(blank=True, null=True)),
                ('utc_time', models.DateTimeField(blank=True, null=True)),
                ('track', models.CharField(max_length=100)),
                ('github_file_url', models.CharField(max_length=100)),
                ('github_repo_url', models.CharField(max_length=100)),
                ('status_code', models.IntegerField(null=True)),
            ],
        ),
    ]
