# Generated by Django 4.2.5 on 2023-09-08 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_alter_slackdetails_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 19, 17, 34, 112333, tzinfo=datetime.timezone.utc)),
        ),
    ]
