# Generated by Django 4.2.5 on 2023-09-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_alter_slackdetails_current_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='current_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
