# Generated by Django 4.2.5 on 2023-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_alter_slackdetails_current_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='track',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
