# Generated by Django 4.2.5 on 2023-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_alter_slackdetails_track_alter_slackdetails_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='current_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slackdetails',
            name='track',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
