# Generated by Django 4.2.5 on 2023-09-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_alter_slackdetails_current_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackdetails',
            name='current_day',
        ),
        migrations.RemoveField(
            model_name='slackdetails',
            name='utc_time',
        ),
    ]
