# Generated by Django 4.2.5 on 2023-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_remove_slackdetails_current_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackdetails',
            name='current_day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
