# Generated by Django 4.2.5 on 2023-09-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_alter_slackdetails_current_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 15, 44, 30, 140037, tzinfo=datetime.timezone.utc)),
        ),
    ]
