# Generated by Django 4.2.5 on 2023-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_slackdetails_current_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackdetails',
            name='utc_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
