# Generated by Django 4.2.5 on 2023-09-09 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0008_alter_slackdetails_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 15, 46, 0, 593170, tzinfo=datetime.timezone.utc)),
        ),
    ]
