# Generated by Django 4.2.5 on 2023-09-09 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_alter_slackdetails_utc_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackdetails',
            old_name='current_day',
            new_name='currentday',
        ),
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 15, 48, 31, 238689, tzinfo=datetime.timezone.utc)),
        ),
    ]
