# Generated by Django 4.2.5 on 2023-09-09 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0010_rename_current_day_slackdetails_currentday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackdetails',
            old_name='currentday',
            new_name='current_day',
        ),
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 15, 50, 14, 628971, tzinfo=datetime.timezone.utc)),
        ),
    ]
