# Generated by Django 4.2.5 on 2023-09-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0011_rename_currentday_slackdetails_current_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackdetails',
            name='utc_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 15, 51, 31, 415503, tzinfo=datetime.timezone.utc)),
        ),
    ]
